# Generated by Django 3.1.10 on 2021-08-21 18:43

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenitiesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, size=[400, 400], upload_to='musics/thumbnails'),
        ),
        migrations.CreateModel(
            name='OpeningHoursModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=1, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.businessprofilemodel')),
            ],
        ),
        migrations.AddField(
            model_name='businessprofilemodel',
            name='amenities',
            field=models.ManyToManyField(to='coreApp.AmenitiesModel'),
        ),
    ]
