# Generated by Django 3.1.10 on 2021-08-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_auto_20210822_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghoursmodel',
            name='weekday',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Satday'), ('7', 'Sunday')], max_length=1, unique=True),
        ),
    ]
