# Generated by Django 3.1.10 on 2021-08-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_auto_20210824_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofilemodel',
            name='category',
            field=models.ManyToManyField(to='coreApp.CategoyModel'),
        ),
    ]
