# Generated by Django 3.1.10 on 2021-09-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0009_auto_20210901_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofilemodel',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='C', max_length=1),
        ),
    ]
