# Generated by Django 3.1.10 on 2021-09-01 08:39

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0010_businessprofilemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofilemodel',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, size=[400, 300], upload_to='businesses/thumbnails'),
        ),
    ]
