# Generated by Django 3.1.10 on 2021-10-17 10:02

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0011_auto_20210901_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofilemodel',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Close')], default='C', max_length=1),
        ),
        migrations.CreateModel(
            name='PreviewImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, size=[700, 415], upload_to='musics/thumbnails')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.businessprofilemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('persons', models.PositiveBigIntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreApp.businessprofilemodel')),
            ],
        ),
    ]
